name: Update Today Date

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 자정 (한국 시간 오전 9시)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Replace TODAY with current date
        run: |
          today=$(date +"%Y-%m-%d")
          sed -i "s/{{TODAY}}/$today/" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update today's date to $today"
          git push
